### ISSUE TITLE
Running on HPC

### ISSUE THREAD

**Issue by asankar** [murphygroup/singularity-cellorganizer#8]
![screen shot 2019-02-06 at 10 43 01 am](https://user-images.githubusercontent.com/10892980/52353186-05f5c100-29fc-11e9-8b6b-f7e324322ef4.png)

Running this script
![image](https://user-images.githubusercontent.com/10892980/52353409-887e8080-29fc-11e9-81db-dae8bec75a0e.png)

**Comment by asankar** [comment]
![image](https://user-images.githubusercontent.com/10892980/52364058-4ceeb100-2a12-11e9-8fe3-4acdc595cf0f.png)
Seg fault with matlab using new 16.04 image

**Comment by icaoberg** [comment]
Issue was fixed.
